all:
  children:
    cloud:
      hosts:
        web.vicchi.org:
          uptime_host: uptime.vicchi.org
          analytics_host: analytics.vicchi.org

  vars:
    ansible_user: ubuntu
    deploy_root: /var/www
    deploy_dir: monitoring-stack
    datastore_dir: data-stores
    deploy_user: ubuntu
    deploy_group: ubuntu
    traefik_network: vicchi-backend
    compose_project: monitoring-stack
