all:
  children:
    uptime:
      hosts:
        web.vicchi.org:
          uptime_host: uptime.vicchi.org
          deploy_dir: uptime
          compose_project: uptime

    analytics:
      hosts:
        ssh.vaguelyrudeplacesmap.com:
          analytics_host: analytics.vicchi.org
          deploy_dir: analytics
          compose_project: analytics

  vars:
    ansible_user: ubuntu
    deploy_root: /var/www
    datastore_dir: data-stores
    deploy_user: ubuntu
    deploy_group: ubuntu
    traefik_network: vicchi-backend
